/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        tertiary: "#ffd2d3",
        "primary-fixed": "#a2eeff",
        "on-secondary-fixed-variant": "#005236",
        "on-tertiary-fixed-variant": "#92002a",
        "on-secondary-container": "#00311f",
        "surface-dim": "#101416",
        "outline-variant": "#3c494c",
        "on-tertiary": "#67001b",
        "on-error": "#690005",
        "surface-container": "#1c2022",
        "surface-variant": "#313538",
        "surface-container-lowest": "#0b0f11",
        background: "#05080A",
        "on-primary-container": "#005763",
        surface: "#101416",
        "on-surface": "#e0e3e6",
        "surface-container-low": "#181c1e",
        "on-primary-fixed": "#001f25",
        "secondary-fixed": "#6ffbbe",
        outline: "#859397",
        "surface-container-high": "#272a2d",
        "on-secondary": "#003824",
        "tertiary-fixed": "#ffdadb",
        "primary-fixed-dim": "#2fd9f4",
        primary: "#8aebff",
        "on-primary-fixed-variant": "#004e5a",
        "surface-container-highest": "#313538",
        "inverse-surface": "#e0e3e6",
        "inverse-primary": "#006877",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-tertiary-container": "#a0002f",
        "primary-container": "#22d3ee",
        "on-secondary-fixed": "#002113",
        "tertiary-container": "#ffaaaf",
        secondary: "#4edea3",
        "on-surface-variant": "#bbc9cd",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#40000d",
        "secondary-fixed-dim": "#4edea3",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        "secondary-container": "#00a572",
        "on-background": "#e0e3e6",
        "surface-bright": "#363a3c",
        "on-primary": "#00363e",
        "inverse-on-surface": "#2d3133",
        "surface-tint": "#2fd9f4"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "element-gap": "16px",
        "container-padding-mobile": "24px",
        unit: "8px",
        "container-padding-desktop": "48px",
        gutter: "24px"
      },
      fontFamily: {
        "display-lg-mobile": ["Hanken Grotesk"],
        "label-md": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "display-lg-mobile": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "300"}],
        "label-md": ["14px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "500"}],
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "300"}]
      }
    },
  },
  plugins: [],
}
